services:
  app:
    build: .
    container_name: cinedaltons-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cinedaltonsdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - cinedaltons-network

  db:
    image: postgres:16-alpine
    container_name: cinedaltons-db
    environment:
      - POSTGRES_DB=cinedaltonsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cinedaltons-network

volumes:
  db_data:

networks:
  cinedaltons-network: